# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "DaaM: Data as a Measurement"
subtitle: hi
email: "phillip.h.rogers@accenture.com"
description: |+
  Ideas, reviews, and rants on machine intelligence, augmented experiences, and data.

  The views and opinions expressed on this site are those of the author and do not necessarily reflect the official policy or position of Accenture, LLP.
baseurl: # the subpath of your site, e.g. /blog
url: "http://DrPinkACN.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  DrPinkACN
#linkedin_username: pro9er5
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
